### ISSUE TITLE
should do verify when component init

### ISSUE THREAD

**Issue by LemonNekoGH** [LittleSound/slimeform#52]
I specified a rule, if the `sample` field is `''`, it will produce error, but this rule not works when the component init. [Sample](https://play.vuejs.org/#__DEV__eNp9Ustu4zAM/BVCFydAbGEfwAKGnc0etl+hi5swrdroAYpKCxj+91JOYrQFWt/IGc6QY43qX4zNOaNqVZf2ZCNDQs4RToN/6I3iZNTWeOtiIIYRCI8wwZGCg0rGqndQTngXyC1wOlmHR+kIyfh98KmwSmMDiQfOSaj9bWw1CosL2sJqDf0WViOkwcUTtlBVMK03xgNQLrVwQb4bvLI8T1iGvu8L+y9USBSoghaYMhb+ZPy0Nr7TlzvlKikYRWJglAqge/yxHcV1Xq65qDc2/S9KME2dFnzmWR8zw7l24YAnSamsfeXPcXV60VUbdUmodkNsnlLwEvW8v7kCkvBykVESaqmNemSOqdU6+/j80OyD0zvBNGXPkmt9CG73q/nZ/P6jDzbx+36DydX3FF4SkjgaNSd3FdfSPCPVhP6AhPSt2SfuB8NP2Nemyzv4ymoh7EpiIj3rW9F9nZVuP09Nb9nW6sQ=)

I must manually invoke the `verify` function now. [Sample](https://play.vuejs.org/#__DEV__eNp9Ustu2zAQ/JUFL5IBS0QfQAFBct1D+xW8qPY6YWs+sFy6DQT9e5ayLSQBEp20O7Mz3CEn9SPG9pJRdapPB7KRISHnCOfRPwxGcTJqZ7x1MRDDBIQnmOFEwUElY9ULKCf8FcitcDpbhyfpCMn4Q/CpsEpjC4lHzmkLFyR7epKR4T5eT8Lmwuqg3sCwg3qCNLp4xg6qCubN1ngAyqUWLsh3h2vLy4RlGIahsL9DhUSBKuiAKWPhz8bPG+Ov1rX89fq6uewpBaOIjYxSAfSPn3aT+C/Hba8+rU0/iybMc68FX3jWx8xwaVw44llyKwvc+EuAvV511VZdM2vcGNs/KXgJf9nE3ADJfN3NKIm51EY9MsfUaZ19/PvQHoLTe8E0Zc+SdHMMbv+l/dx+/aaPNvHLfovJNb8p/EtI4mjUkuFNXEtTwmgI/REJ6UOzN9xXhm+w903Xl/Ge1UrYl8REetG3ovt/Ubpfo5qfAVm+8VU=)

**Comment by LittleSound** [comment]
This is a feature, not a bug.
The form component usually indicates what went wrong only after the user has entered something, rather than displaying the form screen and popping up a bunch of errors like "required field not filled" immediately afterwards because the form has no input. So by default, `slimeform` needs to check for valid input only after the content has changed, but you can do this manually at any time.
